# -*- coding: utf-8 -*-
"""NeuralNetworkProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TEirpMGDtz7SkVWCwVbnahxTw6RxFeZj

Importing libraries 
numpy - numerical python
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix

from google.colab import files

uploaded = files.upload()

import io

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

df = pd.read_csv(io.StringIO(uploaded['Experiment 1 train.csv'].decode('utf-8')))
print(df)

df.head()

feature_cols = list(df.columns[1:])
target_col = df.columns[0]

X = df[feature_cols]
y = df[target_col]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
mlp = MLPClassifier(hidden_layer_sizes=(784,100))
mlp.fit(X_train,y_train)

predictions = mlp.predict(X_test)
print(classification_report(y_test,predictions))